# Generated by Django 4.2.7 on 2023-11-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattributes',
            options={'verbose_name_plural': 'Product attributes'},
        ),
    ]
